### YamlMime:Yaml
ms.openlocfilehash: c68e947d5bf295b6461f6b647da34a9d334bd9b3
ms.sourcegitcommit: 20cbc7b52187d61fca294ac2c00146c2c7c6d337
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 01/13/2022
ms.locfileid: "145884991"
name: $(Date:yyyyMMdd)$(Rev:.rr)
jobs:
- job: build_markdown_content
  displayName: Build Markdown Content
  workspace:
    clean: all
  pool:
    vmImage: Ubuntu 16.04
  container:
    image: microsoftlearning/markdown-build:latest
  steps:
  - task: Bash@3
    displayName: Build Content
    inputs:
      targetType: inline
      script: >
        cp /{attribution.md,template.docx,package.json,package.js} .

        npm install

        node package.js --version $(Build.BuildNumber)
  - task: GitHubRelease@0
    displayName: Create GitHub Release
    inputs:
      gitHubConnection: github-microsoftlearning-organization
      repositoryName: $(Build.Repository.Name)
      tagSource: manual
      tag: v$(Build.BuildNumber)
      title: バージョン $(Build.BuildNumber)
      releaseNotesSource: input
      releaseNotes: '# Version $(Build.BuildNumber) Release'
      assets: $(Build.SourcesDirectory)/out/*.zip
      assetUploadMode: replace
  - task: PublishBuildArtifacts@1
    displayName: Publish Output Files
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/out/
      artifactName: Lab Files
