### YamlMime:Yaml
ms.openlocfilehash: 56ad70a8de3b26c5c6a5396cdf7d484a4a78ef1d
ms.sourcegitcommit: 20cbc7b52187d61fca294ac2c00146c2c7c6d337
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 01/13/2022
ms.locfileid: "145884993"
name: フィードバック レポート
description: フィードバック レポートを提出する
title: M00-LAB00:QUICK_DESCRIPTION
labels:
- feedback
body:
- type: markdown
  attributes:
    value: >
      # Thanks for taking the time to fill out this feedback report!


      **Replace feedback name M00-LAB00:QUICK_DESCRIPTION, for example "M01-LAB01: My new feedback"**
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: "さらに情報が必要な場合は、どうすれば連絡を取ることができますか \U0001F609。"
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What should we change?
    description: 何を変更する必要がありますか。
    placeholder: Tell us your proposal!
    value: PROPOSAL
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Lab
    description: ラボ名
    options:
    - Other
    - Lab 01 Exercise 01 Explore Microsoft 365 Defender
    - Lab 02 Exercise 01 Deploy Microsoft Defender for Endpoint
    - Lab 02 Exercise 02 Mitigate Attacks with Microsoft Defender for Endpoint
    - Lab 03 Exercise 01 Enable Microsoft Defender for Cloud
    - Lab 03 Exercise 02 Mitigate threats using Microsoft Defender for Cloud
    - Lab 04 Exercise 01 Create queries for Microsoft Sentinel using Kusto Query Language (KQL)
    - Lab 05 Exercise 01 Configure your Microsoft Sentinel environment
    - Lab 06 Exercise 01 Connect data to Microsoft Sentinel using data connectors
    - Lab 06 Exercise 02 Connect Windows devices to Microsoft Sentinel using data connectors
    - Lab 06 Exercise 03 Connect Linux hosts to Microsoft Sentinel using data connectors
    - Lab 06 Exercise 04 Connect Threat intelligence to Microsoft Sentinel using data connectors
    - Lab 07 Exercise 01 Activate a Microsoft Security rule
    - Lab 07 Exercise 02 Create a Playbook
    - Lab 07 Exercise 03 Create a Scheduled Query
    - Lab 07 Exercise 04 Understand Detection Modeling
    - Lab 07 Exercise 05 Conduct attacks
    - Lab 07 Exercise 06 Create Detections
    - Lab 07 Exercise 07 Investigate Incidents
    - Lab 07 Exercise 08 Create workbooks
    - Lab 08 Exercise 01 Perform Threat Hunting in Microsoft Sentinel
    - Lab 08 Exercise 02 Threat Hunting using Notebooks with Microsoft Sentinel
  validations:
    required: true
- type: textarea
  id: Screenshots
  attributes:
    label: Relevant screenshots
    description: "関連するスクリーンショットをコピーして貼り付けてください \U0001F4F8"
    value: "paste here \U0001F609"
